### ISSUE TITLE
Consider using GH pages

### ISSUE THREAD

**Issue by mrexodia** [0xZ0F/Z0FCourse_ReverseEngineering#1]
As the title says, consider using github pages to have an improved interface for the course. You should be able to pretty much enable GH pages and forget about it, since it supports markdown.

**Comment by 0xZ0F** [comment]
I've used Github Pages in the past, but I didn't really like it. It looks better than GH, but I really like being able to navigate the course with the GH file structure layout. I plan on reworking the course soon because it could be a lot better. After that, I will certainly look for a new place to host the course.

**Comment by hollasch** [comment]
Sorry to randomize you, but you might be interested in [Markdeep](https://casual-effects.com/markdeep). Markdown-like formatting (with many advanced features), renderable in a standard HTML browser.

See https://raytracing.github.io (click on any of the three books) for an example using a combination of Markdeep and GitHub pages. Not involved in Markdeep, but a huge fan.
