### ISSUE TITLE
Make the course radare2/cutter-friendly

### ISSUE THREAD

**Issue by XVilka** [0xZ0F/Z0FCourse_ReverseEngineering#2]
I noticed you recommend Ghidra, but it is not the only one tool available.
[Radare2](https://github.com/radareorg/radare2) is a highly-portable cross-platform reverse engineering framework and a toolkit without dependencies.  It has support for analyzing binaries, disassembling code, debugging programs, attaching to remote GDB/LLDB, WinDbg servers, rich plugin system (see `r2pm`), and integration with various decompilers. For example, ghidra decompiler plugin - [r2ghidra-dec](https://github.com/radareorg/r2ghidra-dec). It is actively developed and can be easily integrated in various open source and commercial products. 

![image](https://user-images.githubusercontent.com/203261/68269641-7ae24e00-0095-11ea-95f2-cebbc7246954.png)

For general documentation I recommend our constantly updated [Radare2 Book](https://radare.gitbooks.io/radare2book).
For documentation on writing plugins for radare2 see [Scripting](https://radare.gitbooks.io/radare2book/content/scripting/intro.html) and [Plugins](https://radare.gitbooks.io/radare2book/content/plugins/intro.html) Radare2 Book chapters.

[Cutter](https://cutter.re/) is a crossplatform Qt/C++ GUI frontend to radare2:

![image](https://user-images.githubusercontent.com/203261/68269343-78332900-0094-11ea-8646-f6226cb6043f.png)

For documentation on writing plugins for Cutter see [the official tutorial](https://cutter.re/docs/plugins.html) and the [curated list](https://github.com/radareorg/cutter-plugins) of various popular plugins.

**Comment by 0xZ0F** [comment]
Thank you for the recommendation. I'm aware of Radare2, and I did mention it (well, Radare not Radare2 so I'll update that) in [0x002-Setup.md](https://github.com/0xZ0F/Z0FCourse_ReverseEngineering/blob/master/0x000-Introduction/0x002-Setup.md). I'm all for open source and community-focused software like Radare2. I have used Radare2 and Cutter in the past. Unfortunately, I don't have much experience with it, which is why I use Ghidra and x64dbg which I do have experience with. I've wanted to get back into Radare2 because I liked it, however, right now I'm focused on other things. In the future, I will definitely learn how to use Radare2 and from there I will consider if I want to use them for the course.
 
Also, it's difficult to teach while showing multiple different reversing tools doing the same thing. It creates a lot of clutter very quickly. So that's another thing I will have to consider. 

Once again, thank you for the suggestion!
