### ISSUE TITLE
Consider using Cutter or IDA (Freeware or Pro) for example along with x64dbg.

### ISSUE THREAD

**Issue by HarshilPatel007** [0xZ0F/Z0FCourse_ReverseEngineering#24]
Hey 0xZ0F,
this is great tutorials for beginners like me. I want to suggest you to consider using Cutter or IDA  (Freeware or Pro) for the assembly part.
Q. : Why..??? any particular reason..??
A. : Most of the malware analyst spent their time with IDA or students like me who want to learn malware analysis with opensource tools use Cutter for initial days in their learning journey and I see most of the exploit developers are using x64dgb.
So, adding IDA and Cutter examples would help in both MA and RE.
I know their would be no difference in assembly part. but, if we add, then it'd cover most probably entire RE and MA field.

**Comment by 0xZ0F** [comment]
I do plan on implementing at least IDA in the future.

x64dbg is what I'm most comfortable with since it's more tailored to what I do, which is why I chose it. I do plan on adding a lot more to the course including using other tools. I also have plans to add significantly more content and more detailed content. This will include a long static analysis section and a long dynamic analysis section. When I finally get around to developing that, I will probably use IDA and Ghidra for static, and x64dbg for dynamic. I'm not sure if I'll use Cutter as I've barely used it, but I will take a look at it as I've been recommended it in the past.

All of this is after I find the time to work on the course. Currently, I'm in some pretty time-consuming training so don't expect anything soon, but I will try my best! Thank you for your feedback.
